// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmKXj_PpGleCwOuI68Ab-zShrWC-jt4tA',
    appId: '1:970515448651:web:f2296dc1b943027e691ece',
    messagingSenderId: '970515448651',
    projectId: 'srcproject-2fcf5',
    authDomain: 'srcproject-2fcf5.firebaseapp.com',
    storageBucket: 'srcproject-2fcf5.firebasestorage.app',
    measurementId: 'G-SEDMW4263P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqxouUbSnBcA714JRatJ9V2n-jY9Z-ldc',
    appId: '1:970515448651:android:8d36b599fbfd9ec1691ece',
    messagingSenderId: '970515448651',
    projectId: 'srcproject-2fcf5',
    storageBucket: 'srcproject-2fcf5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXUNmbYvMaoKRv1U2MHlfrMqL7tn7GE1k',
    appId: '1:970515448651:ios:c8d90eba6dca61be691ece',
    messagingSenderId: '970515448651',
    projectId: 'srcproject-2fcf5',
    storageBucket: 'srcproject-2fcf5.firebasestorage.app',
    iosBundleId: 'com.example.card',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXUNmbYvMaoKRv1U2MHlfrMqL7tn7GE1k',
    appId: '1:970515448651:ios:c8d90eba6dca61be691ece',
    messagingSenderId: '970515448651',
    projectId: 'srcproject-2fcf5',
    storageBucket: 'srcproject-2fcf5.firebasestorage.app',
    iosBundleId: 'com.example.card',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyLeeryyM2_CbIGdpOkhRg94t8ldXC8nc',
    appId: '1:970515448651:web:f7b3fafbd94127db691ece',
    messagingSenderId: '970515448651',
    projectId: 'srcproject-2fcf5',
    authDomain: 'srcproject-2fcf5.firebaseapp.com',
    storageBucket: 'srcproject-2fcf5.firebasestorage.app',
    measurementId: 'G-2RHVWZ90LF',
  );
}
